//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place_Order
    {
        public string rupya { get; set; }
        public string ph { get; set; }
        public string pin { get; set; }
        public string paisa { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string countrycode { get; set; }
        public string country { get; set; }
        public string buyerlname { get; set; }
        public string buyerfname { get; set; }
        public string address { get; set; }
        public string state { get; set; }
    }
}
